This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./scienceThesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file scienceThesis.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (12 comparisons).
Generating output file scienceThesis.acr....done (15 lines written, 0 warnings).
Output written in scienceThesis.acr.
Transcript written in scienceThesis.alg.
